### ISSUE TITLE
sidebar out of screen when displaying width tables

### ISSUE THREAD

**Issue by dawnmy** [zce/html5up#5]
I am not sure if the purpose of this repo is to maintain the code and fix issues. html5up is very convenient to use. But I found that it is not very compatible with jQuery table plugins including DataTables and FooTable. When there are too many columns in the table, the sidebar goes out of the screen (top and left position are smaller than zero) under certain screen widths. I was wondering how could I solve this issue?

**Comment by dawnmy** [comment]
Why this issue gets closed??

**Comment by zce** [comment]
This is not a issue that the template itself needs to solve, The template does not determine what scenarios users will use it in
